controller:
  allowSnippetAnnotations: true
  metrics:
    enabled: true
  podAnnotations:
    controller:
      metrics:
        service:
          servicePort: "9090"
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  replicaCount: 2
  service:
    type: LoadBalancer