# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l

  setup:
    desc: "Setup the project"
    cmds:
      - brew install tmux
      - brew install overmind

  run:
    desc: "Run the server and the applications"
    deps:
      - setup
      - setup_mongo
      - setup_server
      - setup_admin
      - setup_catalog
    cmds:
      - overmind start

  setup_server:
    desc: "Install air"
    internal: true
    cmds:
      - command -v go || brew install go
      - command -v air || go install github.com/air-verse/air@latest

  setup_admin:
    desc: "Install admin dependencies"
    internal: true
    dir: admin/app
    cmds:
      - npm install

  setup_catalog:
    desc: "Install catalog dependencies"
    internal: true
    dir: catalog/app
    cmds:
      - npm install

  server:
    env:
      ENVIRONMENT: development
    desc: "Run the server"
    interactive: true
    deps:
      - setup_server
    cmds:
      - air

  admin:
    desc: "Run the admin application"
    deps:
      - setup_admin
    dir: admin/app
    cmds:
      - npm run dev

  admin-test:
    desc: "Run the admin tests"
    deps:
      - setup_admin_npm
    dir: admin/app
    cmds:
      - npm run test:unit
    
  admin-build:
    desc: "Build the admin application"
    deps:
      - setup_admin_npm
    dir: admin/app
    sources:
      - index.html
      - src/**/*
    generates:
      - dist
    cmds:
      - npm run build

  catalog:
    desc: "Run the catalog application"
    deps:
      - setup_catalog
    dir: catalog/app
    cmds:
      - npm run dev

  catalog-test:
    desc: "Run the catalog tests"
    deps:
      - setup_catalog_npm
    dir: catalog/app
    cmds:
      - npm run test:unit
    
  catalog-build:
    desc: "Build the catalog application"
    deps:
      - setup_catalog_npm
    dir: catalog/app
    sources:
      - index.html
      - src/**/*
    generates:
      - dist
    cmds:
      - npm run build

  setup_mongo:
    desc: "Setup the MongoDB"
    status:
      - docker ps | grep mongo
    cmds:
      - docker run --name mongo -p 27017:27017 -d mongo:7.0