# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
  
  setup:
    desc: "Install dependencies"
    internal: true
    cmds:
      - task: setup_go
      - task: setup_air

  setup_go:
    desc: "Install go"
    internal: true
    cmds:
      - command -v go || brew install go

  setup_air:
    desc: "Install air"
    internal: true
    deps: 
      - setup_go
    cmds:
      - command -v air || go install github.com/cosmtrek/air@latest

  setup_admin_npm:
    desc: "Install admin dependencies"
    internal: true
    dir: admin/app
    cmds:
      - npm install

  setup_catalog_npm:
    desc: "Install catalog dependencies"
    internal: true
    dir: catalog/app
    cmds:
      - npm install

  run:
    desc: "Run the application"
    deps: ["server", "admin", "catalog"]

  server:
    env:
      ENVIRONMENT: development
    desc: "Run the server"
    interactive: true
    deps:
      - setup_air
    cmds:
      - air

  admin:
    desc: "Run the admin application"
    deps:
      - setup_admin_npm
    dir: admin/app
    cmds:
      - npm run dev

  admin-test:
    desc: "Run the admin tests"
    deps:
      - setup_admin_npm
    dir: admin/app
    cmds:
      - npm run test:unit
    
  admin-build:
    desc: "Build the admin application"
    deps:
      - setup_admin_npm
    dir: admin/app
    sources:
      - index.html
      - src/**/*
    generates:
      - dist
    cmds:
      - npm run build

  catalog:
    desc: "Run the catalog application"
    deps:
      - setup_catalog_npm
    dir: catalog/app
    cmds:
      - npm run dev

  catalog-test:
    desc: "Run the catalog tests"
    deps:
      - setup_catalog_npm
    dir: catalog/app
    cmds:
      - npm run test:unit
    
  catalog-build:
    desc: "Build the catalog application"
    deps:
      - setup_catalog_npm
    dir: catalog/app
    sources:
      - index.html
      - src/**/*
    generates:
      - dist
    cmds:
      - npm run build