---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terpcatalog
  labels:
    app: terpcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terpcatalog
  template:
    metadata:
      labels:
        app: terpcatalog
    spec:
      containers:
        - name: terpcatalog
          image: ghcr.io/campbel/terpcatalog:main
          ports:
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: PORT
              value: "8000"
            - name: ADMIN_PORT
              value: "8001"
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connection_string
            - name: EMAIL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: email
                  key: token
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
