---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terpcatalog
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - terpcatalog.campbel.io
      secretName: terpcatalog
  rules:
    - host: terpcatalog.campbel.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: terpcatalog
                port:
                  number: 80
