---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terpcatalog
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: terpcatalog.campbel.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: terpcatalog
                port:
                  number: 80
