name: build-and-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Build the Docker image
        run: docker build --tag registry.digitalocean.com/tiny-tunnel-registry/terpcatalog:${{ github.sha }} .

      - name: Push the Docker image to the Docker registry
        run: docker push registry.digitalocean.com/tiny-tunnel-registry/terpcatalog:${{ github.sha }}

      - name: Compile the Kubernetes deployment manifest
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: cat infrastructure/kubernetes/manifests/* | envsubst | tee infrastructure/kubernetes/deploy.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: deploy.yaml
          path: infrastructure/kubernetes/deploy.yaml

      - name: Set kubeconfig file
        run: echo "${{ secrets.KUBE_CONFIG }}" > ./config

      - name: Deploy to Kubernetes
        run: kubectl --kubeconfig ./config apply -f infrastructure/kubernetes/deploy.yaml
