name: deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: envsubst
        run: |
          export IMAGE_TAG=${{ github.sha }}
          cat infrastructure/kubernetes/manifests/* | envsubst | tee infrastructure/kubernetes/deploy.yaml
      - uses: actions/upload-artifact@v3
        with:
          name: deploy.yaml
          path: infrastructure/kubernetes/deploy.yaml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f infrastructure/kubernetes/deploy.yaml